### PR TITLE
Sharing outbox transaction

### LINKED ISSUE #38: Outbox in combination with synchronized storage throws `InvalidOperationException` with Transaction has already committed or rolled back
## Who's affected

Customers using the synchronized storage session in combination with the outbox. 

## Symptoms

When the synchronized storage session is used in combination with the outbox the outbox `Store` operation throws an `InvalidOperationException` with `Transaction has already committed or rolled back`

Simple reproduction steps:

- Enable the outbox
- Access the handler transaction without even using it

The following code illustrates it

```
class PlaceOrderHandler : IHandleMessages<PlaceOrder>
{
    Context testContext;

    public PlaceOrderHandler(Context testContext)
    {
        this.testContext = testContext;
    }

    public async Task Handle(PlaceOrder message, IMessageHandlerContext context)
    {
        var session = context.SynchronizedStorageSession.ServiceFabricSession();
        var stateManager = session.StateManager;
        var handlertransaction = session.Transaction;
        await context.SendLocal(new SendOrderAcknowledgement());
    }
}
```

## Analysis

An issue in our code makes the synchronized storage session always own the transaction even though it is effectively owned by the outbox. Since the synchronized storage session is committed first subsequent access to the transaction in the outbox storage will fail.

### PR DESCRIPTION
**Pull request by danielmarbach**
Fixes #38 

Sharing the outbox transaction with the synchronized storage can lead to InvalidOperationException because the transaction was already committed.

This PR introduces StorageSession that can wrap a SF transaction without owning it. This is the prerequisite to create a correct implementation of `SynchronizedStorageAdapter `that properly propagates transaction, without letting it being committed too early.

### CODE REVIEW

File: src/NServiceBus.Persistence.ServiceFabric/Outbox/OutboxStorage.cs [hunk 1]
```diff
@@ -59,7 +59,7 @@ public Task<OutboxTransaction> BeginTransaction(ContextBag context)
                 operations[i] = new StoredTransportOperation(t.MessageId, t.Options, t.Body, t.Headers);
             }
 
-            var tx = ((ServiceFabricOutboxTransaction) transaction).Transaction.Value;
+            var tx = ((ServiceFabricOutboxTransaction) transaction).Transaction.Transaction;
```
Comment (danielmarbach) [inline src/NServiceBus.Persistence.ServiceFabric/Outbox/OutboxStorage.cs]: Not really proud of this train wreck. But since it was previously also a train wreck I figured I'll leave it at that. If you can come up with any good naming ideas feel free to shoot.

**Comment by danielmarbach** [comment]
@Particular/azure-maintainers please review

File: src/NServiceBus.Persistence.ServiceFabric/Outbox/OutboxStorage.cs (hunk 1 above)
Comment (yvesgoeleven) [inline src/NServiceBus.Persistence.ServiceFabric/Outbox/OutboxStorage.cs]: .Transaction.NativeTransaction ?

File: src/NServiceBus.Persistence.ServiceFabric/SynchronizedStorage/SynchronizedStorageAdapter.cs [hunk 2]
```diff
@@ -12,7 +12,7 @@ public Task<CompletableSynchronizedStorageSession> TryAdapt(OutboxTransaction tr
             var outboxTransaction = transaction as ServiceFabricOutboxTransaction;
             if (outboxTransaction != null)
             {
-                CompletableSynchronizedStorageSession session = new StorageSession(outboxTransaction.StateManager, outboxTransaction.Transaction);
+                CompletableSynchronizedStorageSession session = new StorageSession(outboxTransaction.Transaction);
```
Comment (danielmarbach) [inline src/NServiceBus.Persistence.ServiceFabric/SynchronizedStorage/SynchronizedStorageAdapter.cs]: A good suggestion will do.

**Comment by danielmarbach** [comment]
@Scooletz pushed an update

**Comment by Scooletz** [comment]
LGTM @danielmarbach

**Comment by danielmarbach** [comment]
Since approved I'll merge this
